# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from proovid_python_sdk.paths.api_address_natural_person_elv.post import CreateNaturalPersonElvRaw
from proovid_python_sdk.paths.api_address_link_response.post import LinkResponseRaw
from proovid_python_sdk.paths.api_address_address_verification_id.get import VerifyByIdRaw
from proovid_python_sdk.paths.api_address_address_verification_id.delete import VerifyById0Raw
from proovid_python_sdk.paths.api_address_verification_by_level.post import VerifyByLevelRaw
from proovid_python_sdk.paths.api_address_address_verification_id_certificate_pdf.get import VerifyCertificatePdfRaw


class AddressApiRaw(
    CreateNaturalPersonElvRaw,
    LinkResponseRaw,
    VerifyByIdRaw,
    VerifyById0Raw,
    VerifyByLevelRaw,
    VerifyCertificatePdfRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
