# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from proovid_python_sdk.paths.api_address_natural_person_elv.post import CreateNaturalPersonElv
from proovid_python_sdk.paths.api_address_link_response.post import LinkResponse
from proovid_python_sdk.paths.api_address_address_verification_id.get import VerifyById
from proovid_python_sdk.paths.api_address_address_verification_id.delete import VerifyById0
from proovid_python_sdk.paths.api_address_verification_by_level.post import VerifyByLevel
from proovid_python_sdk.paths.api_address_address_verification_id_certificate_pdf.get import VerifyCertificatePdf
from proovid_python_sdk.apis.tags.address_api_raw import AddressApiRaw


class AddressApi(
    CreateNaturalPersonElv,
    LinkResponse,
    VerifyById,
    VerifyById0,
    VerifyByLevel,
    VerifyCertificatePdf,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AddressApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AddressApiRaw(api_client)
