# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from proovid_python_sdk.paths.api_document_document_verification_id_certificate_pdf.get import GetCertificate
from proovid_python_sdk.paths.api_document_document_verification_id.delete import VerifyDeletion
from proovid_python_sdk.paths.api_document_document_verification_id.get import VerifyStatus
from proovid_python_sdk.paths.api_document_verify_document.post import VerifyStatus0
from proovid_python_sdk.apis.tags.document_api_raw import DocumentApiRaw


class DocumentApi(
    GetCertificate,
    VerifyDeletion,
    VerifyStatus,
    VerifyStatus0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DocumentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DocumentApiRaw(api_client)
