# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from proovid_python_sdk.paths.api_document_document_verification_id_certificate_pdf.get import GetCertificateRaw
from proovid_python_sdk.paths.api_document_document_verification_id.delete import VerifyDeletionRaw
from proovid_python_sdk.paths.api_document_document_verification_id.get import VerifyStatusRaw
from proovid_python_sdk.paths.api_document_verify_document.post import VerifyStatus0Raw


class DocumentApiRaw(
    GetCertificateRaw,
    VerifyDeletionRaw,
    VerifyStatusRaw,
    VerifyStatus0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
