# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from proovid_python_sdk.paths.api_natural_person.post import CreateOrUpdate
from proovid_python_sdk.paths.api_natural_person_id.delete import DeleteById
from proovid_python_sdk.paths.api_natural_person_id.get import GetById
from proovid_python_sdk.paths.api_natural_person_reference.get import GetById0
from proovid_python_sdk.paths.api_natural_person_natural_person_id_certificate.get import GetCertificate
from proovid_python_sdk.paths.api_natural_person_natural_person_id_get.get import GetDetails
from proovid_python_sdk.paths.api_natural_person_verification_record_verification_id.get import GetVerificationRecord
from proovid_python_sdk.paths.api_natural_person_natural_person_id_verifications.get import GetVerifications
from proovid_python_sdk.paths.api_natural_person_natural_person_id_delete.delete import RemoveById
from proovid_python_sdk.paths.api_natural_person_natural_person_id_update_documents.post import UpdateDocuments
from proovid_python_sdk.paths.api_natural_person_natural_person_id_update_info.post import UpdateInformation
from proovid_python_sdk.paths.api_natural_person_verify.post import VerifyDetails
from proovid_python_sdk.paths.api_natural_person_natural_person_id_verify.post import VerifyDetails0
from proovid_python_sdk.paths.api_natural_person_natural_person_id_update_documents_verify.post import VerifyDocuments
from proovid_python_sdk.paths.api_natural_person_verifyentity.post import VerifyEntity
from proovid_python_sdk.apis.tags.natural_person_api_raw import NaturalPersonApiRaw


class NaturalPersonApi(
    CreateOrUpdate,
    DeleteById,
    GetById,
    GetById0,
    GetCertificate,
    GetDetails,
    GetVerificationRecord,
    GetVerifications,
    RemoveById,
    UpdateDocuments,
    UpdateInformation,
    VerifyDetails,
    VerifyDetails0,
    VerifyDocuments,
    VerifyEntity,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NaturalPersonApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NaturalPersonApiRaw(api_client)
