# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from proovid_python_sdk.paths.api_natural_person.post import CreateOrUpdateRaw
from proovid_python_sdk.paths.api_natural_person_id.delete import DeleteByIdRaw
from proovid_python_sdk.paths.api_natural_person_id.get import GetByIdRaw
from proovid_python_sdk.paths.api_natural_person_reference.get import GetById0Raw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_certificate.get import GetCertificateRaw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_get.get import GetDetailsRaw
from proovid_python_sdk.paths.api_natural_person_verification_record_verification_id.get import GetVerificationRecordRaw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_verifications.get import GetVerificationsRaw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_delete.delete import RemoveByIdRaw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_update_documents.post import UpdateDocumentsRaw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_update_info.post import UpdateInformationRaw
from proovid_python_sdk.paths.api_natural_person_verify.post import VerifyDetailsRaw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_verify.post import VerifyDetails0Raw
from proovid_python_sdk.paths.api_natural_person_natural_person_id_update_documents_verify.post import VerifyDocumentsRaw
from proovid_python_sdk.paths.api_natural_person_verifyentity.post import VerifyEntityRaw


class NaturalPersonApiRaw(
    CreateOrUpdateRaw,
    DeleteByIdRaw,
    GetByIdRaw,
    GetById0Raw,
    GetCertificateRaw,
    GetDetailsRaw,
    GetVerificationRecordRaw,
    GetVerificationsRaw,
    RemoveByIdRaw,
    UpdateDocumentsRaw,
    UpdateInformationRaw,
    VerifyDetailsRaw,
    VerifyDetails0Raw,
    VerifyDocumentsRaw,
    VerifyEntityRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
