# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from proovid_python_sdk import schemas  # noqa: F401


class RejectLabelType(
    schemas.EnumBase,
    schemas.Int32Schema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def POSITIVE_0(cls):
        return cls(0)
    
    @schemas.classproperty
    def POSITIVE_1(cls):
        return cls(1)
    
    @schemas.classproperty
    def POSITIVE_2(cls):
        return cls(2)
    
    @schemas.classproperty
    def POSITIVE_3(cls):
        return cls(3)
    
    @schemas.classproperty
    def POSITIVE_4(cls):
        return cls(4)
    
    @schemas.classproperty
    def POSITIVE_5(cls):
        return cls(5)
    
    @schemas.classproperty
    def POSITIVE_6(cls):
        return cls(6)
    
    @schemas.classproperty
    def POSITIVE_7(cls):
        return cls(7)
    
    @schemas.classproperty
    def POSITIVE_8(cls):
        return cls(8)
    
    @schemas.classproperty
    def POSITIVE_9(cls):
        return cls(9)
    
    @schemas.classproperty
    def POSITIVE_10(cls):
        return cls(10)
    
    @schemas.classproperty
    def POSITIVE_11(cls):
        return cls(11)
    
    @schemas.classproperty
    def POSITIVE_12(cls):
        return cls(12)
    
    @schemas.classproperty
    def POSITIVE_13(cls):
        return cls(13)
    
    @schemas.classproperty
    def POSITIVE_14(cls):
        return cls(14)
    
    @schemas.classproperty
    def POSITIVE_15(cls):
        return cls(15)
    
    @schemas.classproperty
    def POSITIVE_16(cls):
        return cls(16)
    
    @schemas.classproperty
    def POSITIVE_17(cls):
        return cls(17)
    
    @schemas.classproperty
    def POSITIVE_18(cls):
        return cls(18)
    
    @schemas.classproperty
    def POSITIVE_19(cls):
        return cls(19)
    
    @schemas.classproperty
    def POSITIVE_20(cls):
        return cls(20)
    
    @schemas.classproperty
    def POSITIVE_21(cls):
        return cls(21)
    
    @schemas.classproperty
    def POSITIVE_22(cls):
        return cls(22)
    
    @schemas.classproperty
    def POSITIVE_23(cls):
        return cls(23)
    
    @schemas.classproperty
    def POSITIVE_24(cls):
        return cls(24)
    
    @schemas.classproperty
    def POSITIVE_25(cls):
        return cls(25)
    
    @schemas.classproperty
    def POSITIVE_26(cls):
        return cls(26)
    
    @schemas.classproperty
    def POSITIVE_27(cls):
        return cls(27)
    
    @schemas.classproperty
    def POSITIVE_28(cls):
        return cls(28)
    
    @schemas.classproperty
    def POSITIVE_29(cls):
        return cls(29)
    
    @schemas.classproperty
    def POSITIVE_30(cls):
        return cls(30)
    
    @schemas.classproperty
    def POSITIVE_31(cls):
        return cls(31)
    
    @schemas.classproperty
    def POSITIVE_32(cls):
        return cls(32)
    
    @schemas.classproperty
    def POSITIVE_33(cls):
        return cls(33)
    
    @schemas.classproperty
    def POSITIVE_34(cls):
        return cls(34)
    
    @schemas.classproperty
    def POSITIVE_35(cls):
        return cls(35)
    
    @schemas.classproperty
    def POSITIVE_36(cls):
        return cls(36)
    
    @schemas.classproperty
    def POSITIVE_37(cls):
        return cls(37)
    
    @schemas.classproperty
    def POSITIVE_38(cls):
        return cls(38)
    
    @schemas.classproperty
    def POSITIVE_39(cls):
        return cls(39)
    
    @schemas.classproperty
    def POSITIVE_40(cls):
        return cls(40)
    
    @schemas.classproperty
    def POSITIVE_41(cls):
        return cls(41)
    
    @schemas.classproperty
    def POSITIVE_42(cls):
        return cls(42)
    
    @schemas.classproperty
    def POSITIVE_43(cls):
        return cls(43)
    
    @schemas.classproperty
    def POSITIVE_44(cls):
        return cls(44)
    
    @schemas.classproperty
    def POSITIVE_45(cls):
        return cls(45)
    
    @schemas.classproperty
    def POSITIVE_46(cls):
        return cls(46)
    
    @schemas.classproperty
    def POSITIVE_47(cls):
        return cls(47)
    
    @schemas.classproperty
    def POSITIVE_48(cls):
        return cls(48)
    
    @schemas.classproperty
    def POSITIVE_49(cls):
        return cls(49)
    
    @schemas.classproperty
    def POSITIVE_50(cls):
        return cls(50)
    
    @schemas.classproperty
    def POSITIVE_51(cls):
        return cls(51)
    
    @schemas.classproperty
    def POSITIVE_52(cls):
        return cls(52)
    
    @schemas.classproperty
    def POSITIVE_53(cls):
        return cls(53)
    
    @schemas.classproperty
    def POSITIVE_54(cls):
        return cls(54)
