# coding: utf-8

"""
    Proovid Electronic Verification

    Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

    The version of the OpenAPI document: v1
    Contact: info@proovid.com
    Created by: http://www.proovid.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from proovid_python_sdk import schemas  # noqa: F401


class ShuftiAddressData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class issueDate(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'issueDate':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            fullAddress = schemas.AnyTypeSchema
        
            @staticmethod
            def name() -> typing.Type['Name']:
                return Name
        
            @staticmethod
            def selectedType() -> typing.Type['ShuftiAddressDataSelectedType']:
                return ShuftiAddressDataSelectedType
        
            @staticmethod
            def supportedTypes() -> typing.Type['ShuftiAddressDataSupportedTypes']:
                return ShuftiAddressDataSupportedTypes
            __annotations__ = {
                "issueDate": issueDate,
                "fullAddress": fullAddress,
                "name": name,
                "selectedType": selectedType,
                "supportedTypes": supportedTypes,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["issueDate"]) -> MetaOapg.properties.issueDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fullAddress"]) -> MetaOapg.properties.fullAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> 'Name': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["selectedType"]) -> 'ShuftiAddressDataSelectedType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["supportedTypes"]) -> 'ShuftiAddressDataSupportedTypes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["issueDate", "fullAddress", "name", "selectedType", "supportedTypes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["issueDate"]) -> typing.Union[MetaOapg.properties.issueDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fullAddress"]) -> typing.Union[MetaOapg.properties.fullAddress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union['Name', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["selectedType"]) -> typing.Union['ShuftiAddressDataSelectedType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["supportedTypes"]) -> typing.Union['ShuftiAddressDataSupportedTypes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["issueDate", "fullAddress", "name", "selectedType", "supportedTypes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        issueDate: typing.Union[MetaOapg.properties.issueDate, None, str, datetime, schemas.Unset] = schemas.unset,
        fullAddress: typing.Union[MetaOapg.properties.fullAddress, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        name: typing.Union['Name', schemas.Unset] = schemas.unset,
        selectedType: typing.Union['ShuftiAddressDataSelectedType', schemas.Unset] = schemas.unset,
        supportedTypes: typing.Union['ShuftiAddressDataSupportedTypes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ShuftiAddressData':
        return super().__new__(
            cls,
            *args,
            issueDate=issueDate,
            fullAddress=fullAddress,
            name=name,
            selectedType=selectedType,
            supportedTypes=supportedTypes,
            _configuration=_configuration,
            **kwargs,
        )

from proovid_python_sdk.model.name import Name
from proovid_python_sdk.model.shufti_address_data_selected_type import ShuftiAddressDataSelectedType
from proovid_python_sdk.model.shufti_address_data_supported_types import ShuftiAddressDataSupportedTypes
